package POJOS;
// Generated 21-mar-2020 9:41:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comprabackup generated by hbm2java
 */
public class Comprabackup  implements java.io.Serializable {


     private Integer id;
     private Tarjetabackup tarjetabackup;
     private Viajesbackup viajesbackup;
     private Date fechaPago;
     private double importeCompra;
     private int numViajeros;
     private String localizador;
     private Date fechaBaja;
     private Set ocupacionbackups = new HashSet(0);

    public Comprabackup() {
    }

	
    public Comprabackup(Tarjetabackup tarjetabackup, Viajesbackup viajesbackup, Date fechaPago, double importeCompra, int numViajeros, String localizador, Date fechaBaja) {
        this.tarjetabackup = tarjetabackup;
        this.viajesbackup = viajesbackup;
        this.fechaPago = fechaPago;
        this.importeCompra = importeCompra;
        this.numViajeros = numViajeros;
        this.localizador = localizador;
        this.fechaBaja = fechaBaja;
    }
    public Comprabackup(Tarjetabackup tarjetabackup, Viajesbackup viajesbackup, Date fechaPago, double importeCompra, int numViajeros, String localizador, Date fechaBaja, Set ocupacionbackups) {
       this.tarjetabackup = tarjetabackup;
       this.viajesbackup = viajesbackup;
       this.fechaPago = fechaPago;
       this.importeCompra = importeCompra;
       this.numViajeros = numViajeros;
       this.localizador = localizador;
       this.fechaBaja = fechaBaja;
       this.ocupacionbackups = ocupacionbackups;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tarjetabackup getTarjetabackup() {
        return this.tarjetabackup;
    }
    
    public void setTarjetabackup(Tarjetabackup tarjetabackup) {
        this.tarjetabackup = tarjetabackup;
    }
    public Viajesbackup getViajesbackup() {
        return this.viajesbackup;
    }
    
    public void setViajesbackup(Viajesbackup viajesbackup) {
        this.viajesbackup = viajesbackup;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public double getImporteCompra() {
        return this.importeCompra;
    }
    
    public void setImporteCompra(double importeCompra) {
        this.importeCompra = importeCompra;
    }
    public int getNumViajeros() {
        return this.numViajeros;
    }
    
    public void setNumViajeros(int numViajeros) {
        this.numViajeros = numViajeros;
    }
    public String getLocalizador() {
        return this.localizador;
    }
    
    public void setLocalizador(String localizador) {
        this.localizador = localizador;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public Set getOcupacionbackups() {
        return this.ocupacionbackups;
    }
    
    public void setOcupacionbackups(Set ocupacionbackups) {
        this.ocupacionbackups = ocupacionbackups;
    }

   public void setOcupacionbackup(Ocupacionbackup ocupacionbackups) {
        this.ocupacionbackups.add(ocupacionbackups);
    }



}


