package POJOS;
// Generated 21-mar-2020 9:41:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Horarios generated by hbm2java
 */
public class Horarios  implements java.io.Serializable {


     private Integer id;
     private Ruta ruta;
     private Date horaSalida;
     private Date horaLlegada;
     private String tipo;
     private Set viajeses = new HashSet(0);
     private Set viajesbackups = new HashSet(0);

    public Horarios() {
    }

	
    public Horarios(Ruta ruta, Date horaSalida, Date horaLlegada, String tipo) {
        this.ruta = ruta;
        this.horaSalida = horaSalida;
        this.horaLlegada = horaLlegada;
        this.tipo = tipo;
    }
    public Horarios(Ruta ruta, Date horaSalida, Date horaLlegada, String tipo, Set viajeses, Set viajesbackups) {
       this.ruta = ruta;
       this.horaSalida = horaSalida;
       this.horaLlegada = horaLlegada;
       this.tipo = tipo;
       this.viajeses = viajeses;
       this.viajesbackups = viajesbackups;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }
    public Date getHoraLlegada() {
        return this.horaLlegada;
    }
    
    public void setHoraLlegada(Date horaLlegada) {
        this.horaLlegada = horaLlegada;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getViajeses() {
        return this.viajeses;
    }
    
    public void setViajeses(Set viajeses) {
        this.viajeses = viajeses;
    }
    public Set getViajesbackups() {
        return this.viajesbackups;
    }
    
    public void setViajesbackups(Set viajesbackups) {
        this.viajesbackups = viajesbackups;
    }




}


