package POJOS;
// Generated 21-mar-2020 9:41:27 by Hibernate Tools 4.3.1



/**
 * Ocupacion generated by hbm2java
 */
public class Ocupacion  implements java.io.Serializable {


     private Integer id;
     private Compra compra;
     private Viajero viajero;
     private int numAsiento;
     private double importe;

    public Ocupacion() {
    }

    public Ocupacion(Compra compra, Viajero viajero, int numAsiento, double importe) {
       this.compra = compra;
       this.viajero = viajero;
       this.numAsiento = numAsiento;
       this.importe = importe;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Viajero getViajero() {
        return this.viajero;
    }
    
    public void setViajero(Viajero viajero) {
        this.viajero = viajero;
    }
    public int getNumAsiento() {
        return this.numAsiento;
    }
    
    public void setNumAsiento(int numAsiento) {
        this.numAsiento = numAsiento;
    }
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }




}


