package POJOS;
// Generated 21-mar-2020 9:41:27 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ocupacionbackup generated by hbm2java
 */
public class Ocupacionbackup  implements java.io.Serializable {


     private Integer id;
     private Comprabackup comprabackup;
     private Viajerobackup viajerobackup;
     private int numAsiento;
     private double importe;
     private Date fechaBaja;

    public Ocupacionbackup() {
    }

    public Ocupacionbackup(Comprabackup comprabackup, Viajerobackup viajerobackup, int numAsiento, double importe, Date fechaBaja) {
       this.comprabackup = comprabackup;
       this.viajerobackup = viajerobackup;
       this.numAsiento = numAsiento;
       this.importe = importe;
       this.fechaBaja = fechaBaja;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Comprabackup getComprabackup() {
        return this.comprabackup;
    }
    
    public void setComprabackup(Comprabackup comprabackup) {
        this.comprabackup = comprabackup;
    }
    public Viajerobackup getViajerobackup() {
        return this.viajerobackup;
    }
    
    public void setViajerobackup(Viajerobackup viajerobackup) {
        this.viajerobackup = viajerobackup;
    }
    public int getNumAsiento() {
        return this.numAsiento;
    }
    
    public void setNumAsiento(int numAsiento) {
        this.numAsiento = numAsiento;
    }
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }




}


