package POJOS;
// Generated 21-mar-2020 9:41:27 by Hibernate Tools 4.3.1



/**
 * Parametros generated by hbm2java
 */
public class Parametros  implements java.io.Serializable {


     private Integer id;
     private String user;
     private String password;
     private String empresa;
     private String sede;
     private String cif;

    public Parametros() {
    }

    public Parametros(String user, String password, String empresa, String sede, String cif) {
       this.user = user;
       this.password = password;
       this.empresa = empresa;
       this.sede = sede;
       this.cif = cif;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getSede() {
        return this.sede;
    }
    
    public void setSede(String sede) {
        this.sede = sede;
    }
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }




}


