package POJOS;
// Generated 21-mar-2020 9:41:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarjetabackup generated by hbm2java
 */
public class Tarjetabackup  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private String tipo;
     private byte[] num;
     private Date caducidad;
     private int cvv;
     private Date fechaBaja;
     private Set comprabackups = new HashSet(0);

    public Tarjetabackup() {
    }

	
    public Tarjetabackup(Cliente cliente, String tipo, byte[] num, Date caducidad, int cvv, Date fechaBaja) {
        this.cliente = cliente;
        this.tipo = tipo;
        this.num = num;
        this.caducidad = caducidad;
        this.cvv = cvv;
        this.fechaBaja = fechaBaja;
    }
    public Tarjetabackup(Cliente cliente, String tipo, byte[] num, Date caducidad, int cvv, Date fechaBaja, Set comprabackups) {
       this.cliente = cliente;
       this.tipo = tipo;
       this.num = num;
       this.caducidad = caducidad;
       this.cvv = cvv;
       this.fechaBaja = fechaBaja;
       this.comprabackups = comprabackups;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public byte[] getNum() {
        return this.num;
    }
    
    public void setNum(byte[] num) {
        this.num = num;
    }
    public Date getCaducidad() {
        return this.caducidad;
    }
    
    public void setCaducidad(Date caducidad) {
        this.caducidad = caducidad;
    }
    public int getCvv() {
        return this.cvv;
    }
    
    public void setCvv(int cvv) {
        this.cvv = cvv;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public Set getComprabackups() {
        return this.comprabackups;
    }
    
    public void setComprabackups(Set comprabackups) {
        this.comprabackups = comprabackups;
    }




}


