package POJOS;
// Generated 21-mar-2020 9:41:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viajes generated by hbm2java
 */
public class Viajes  implements java.io.Serializable {


     private Integer id;
     private Horarios horarios;
     private Date dia;
     private int plazas;
     private Set compras = new HashSet(0);

    public Viajes() {
    }

	
    public Viajes(Horarios horarios, Date dia, int plazas) {
        this.horarios = horarios;
        this.dia = dia;
        this.plazas = plazas;
    }
    public Viajes(Horarios horarios, Date dia, int plazas, Set compras) {
       this.horarios = horarios;
       this.dia = dia;
       this.plazas = plazas;
       this.compras = compras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Horarios getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Horarios horarios) {
        this.horarios = horarios;
    }
    public Date getDia() {
        return this.dia;
    }
    
    public void setDia(Date dia) {
        this.dia = dia;
    }
    public int getPlazas() {
        return this.plazas;
    }
    
    public void setPlazas(int plazas) {
        this.plazas = plazas;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


