package POJOS;
// Generated 21-mar-2020 9:41:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Viajero generated by hbm2java
 */
public class Viajero  implements java.io.Serializable {


     private Integer id;
     private String dni;
     private String nombre;
     private String apellidos;
     private Set ocupacions = new HashSet(0);

    public Viajero() {
    }

	
    public Viajero(String dni, String nombre, String apellidos) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellidos = apellidos;
    }
    public Viajero(String dni, String nombre, String apellidos, Set ocupacions) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.ocupacions = ocupacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Set getOcupacions() {
        return this.ocupacions;
    }
    
    public void setOcupacions(Set ocupacions) {
        this.ocupacions = ocupacions;
    }

    public void setOcupacion(Ocupacion ocupacions) {
        this.ocupacions.add(ocupacions);
    }



}


